/**
 * Standard disclosure/disclaimer copy. These are placeholders for the skeleton
 * and MUST be reviewed and replaced by a licensed compliance professional
 * before production use. Nothing here constitutes legal or financial advice.
 */
export const DISCLOSURES = {
  financialGeneral:
    'This information is for educational purposes only and is not investment, tax, or legal advice. ' +
    'Any recommendations require review by a licensed advisor and a documented suitability assessment.',
  insuranceGeneral:
    'Plan information is provided for general guidance only and is subject to carrier approval and eligibility. ' +
    'Final coverage decisions require review with a licensed insurance agent.',
  medicare:
    'We do not offer every plan available in your area. Any information we provide is limited to the plans we ' +
    'offer in your area. Please contact Medicare.gov or 1-800-MEDICARE to get information on all of your options.',
  aiGenerated:
    'Portions of this summary were generated by an automated system and require advisor review before use with a client.',
  recordingConsent:
    'This call may be recorded for quality and compliance. Consent is captured before recording begins.',
} as const;

export type DisclosureKey = keyof typeof DISCLOSURES;
